name: qs_audio_player
description: QS Audio Player
version: 0.0.6
homepage: "https://github.com/artsiombarouski/qs_audio_player.git"

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  just_audio: ^0.9.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.qs.audio_player.qs_audio_player
        pluginClass: QsAudioPlayerPlugin
      ios:
        pluginClass: QsAudioPlayerPlugin
